containers:
  - name: k8s-api-gateway
    image: rlaalsdn0421/k8s-api-gateway:0.0.1
    imagePullPolicy: Always
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: dev
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: api-gateway-config-volume
    mountPath: /etc/config
      - name: api-gateway-secret-volume
        mountPath: /etc/secret
    volumes:
      - name: api-gateway-config-volume
        configMap:
          name: api-gateway-config
          items:
            - key: application-dev.yml
              path: application-dev.yml
      - name: api-gateway-secret-volume
        secret:
          secretName: api-gateway-secret
          items:
            - key: application-secret.yml
              path: application-secret.yml